location = /vreports {
    return 301 /vreports/;
}

location ^~ /vreports/css/ {
    alias /apps/vreports/web/css/;
}

location ^~ /vreports/images/ {
    alias /apps/vreports/web/images/;
}

location ^~ /vreports/js/ {
    alias /apps/vreports/web/js/;
}

location /vreports/ {
    access_log /var/log/nginx/vreports/access.log;
    error_log  /var/log/nginx/vreports/error.log;

    include proxy_params;
    proxy_pass http://unix:/apps/vreports/web/vreports.sock;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
